Document: loki
Title: Debian loki Manual
Author: <insert document author here>
Abstract: This manual describes what loki is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/loki/loki.sgml.gz

Format: postscript
Files: /usr/share/doc/loki/loki.ps.gz

Format: text
Files: /usr/share/doc/loki/loki.text.gz

Format: HTML
Index: /usr/share/doc/loki/html/index.html
Files: /usr/share/doc/loki/html/*.html
